### ISSUE TITLE
Blank main page

### ISSUE THREAD

**Issue by davaya** [ScreamBun/electron-schema#2]
I installed the Windows MSI distribution and the user interface works fine - the File / Edit / View / Help menus work.  But the main screen remains blank - there is nothing shown after New or Open.  Presumably Node.js or a Node package need to be installed separately, or configuration to be done, to connect the UI to an application.  Setup should be described in the README, perhaps with a link to npm like https://www.electronjs.org/docs/tutorial/first-app#trying-this-example.

**Comment by ScreamBun** [comment]
Path mistyped for the built application. [v0.1.1](https://github.com/ScreamBun/electron-schema/releases/tag/v0.1.1-alpha) has been release to fix this issue.
